### ISSUE TITLE
Lab repeats the same content from "react-event-system"

### ISSUE THREAD

**Issue by dstoll243** [learn-co-curriculum/react-events-crash-course-readme#2]
One of the two should be removed, as while the wording is slightly different, the content is the same and leads to confusion. I would argue that the "react-event-system" lab should be the one removed, as according to the release calendar, it is to be released second.

Lab with similar content: https://github.com/learn-co-curriculum/react-event-system

**Comment by maxwellbenton** [comment]
Hi @dahby,

Thanks for reporting this. We are aware of this issue and are now tracking this and other order related issues [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3).

We are currently updating and restructuring the materials in this section and will add this to our internal work queue. We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of the React curriculum.

I'm closing this issue but I invite you to follow the progress. We will notify
you here when it is resolved.

Thanks for contributing!
